### ISSUE TITLE
background call issue

### ISSUE THREAD

**Issue by ReactNativeDev2296** [willnaoosmith/React-native-sip-pjsip#10] opened 2021-07-30 06:16 UTC
Hello @willnaoosmith and @tzigdon ,
when get incoming call in background if i accept call under 40 second call is accepted but after 40 call accept not working and getting error TypeError:- call.getState() is not a function.
So can you please help me above issue 

Thank you

**Comment by willnaoosmith** [comment] 2021-07-30 10:57
What's your platform?
Android?
IOS?
What's the version of your platform?

**Comment by ReactNativeDev2296** [comment] 2021-07-30 11:19
Hi @willnaoosmith ,
i am using 
React-native :0.63.4,
Android: 8.1, 9, 10, 11
React-native-pjsip:- 2.7.4,
what is incoming call time without accept(Timeout) ?
**android** **Logs** 
`V/FA: onActivityCreated
V/FA: Connecting to remote service
V/FA: Activity resumed, time: 100069048
V/FA: Connection attempt already in progress
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 2
I/zygote64: Do full code cache collection, code=501KB, data=320KB
I/zygote64: After code cache collection, code=494KB, data=270KB
I/zygote64: Do partial code cache collection, code=501KB, data=284KB
I/zygote64: After code cache collection, code=501KB, data=284KB
    Increasing code cache capacity to 2MB
V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
    cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/MediaPlayer-JNI: MediaPlayer finalized without being released
I/RNPushNotification: Cancelling all notifications
    Clearing alerts from the notification centre
D/PjSipService: On Create Service
    Starting Service
D/PjSipService: Registering PhoneStateChangedReceiver
W/MediaPlayer: Couldn't open content://0@settings/system/ringtone_cache: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
D/Ringtone: Successfully created local player
D/PjSipService: pack: com.logicmark.connectedguardian
D/PjSipService: Ringback uri: android.resource://com.logicmark.connectedguardian/raw/ringback
D/PjSipLogWriter: 16:39:58.688         sip_endpoint.c !.Module "mod-pjsua-log" registered
    16:39:58.688         sip_endpoint.c  .Module "mod-tsx-layer" registered
    16:39:58.688         sip_endpoint.c  .Module "mod-stateful-util" registered
    16:39:58.688         sip_endpoint.c  .Module "mod-ua" registered
    16:39:58.688         sip_endpoint.c  .Module "mod-100rel" registered
    16:39:58.688         sip_endpoint.c  .Module "mod-pjsua" registered
D/PjSipLogWriter: 16:39:58.689         sip_endpoint.c  .Module "mod-invite" registered
    16:39:58.689           opensl_dev.c  ..OpenSL sound library initialized
D/PjSipLogWriter: 16:39:58.690                  pjlib  ..select() I/O Queue created (0x6fc535e828)
    16:39:58.690           conference.c  ..Creating conference bridge with 12 ports
    16:39:58.690           Master/sound  ..Using delay buffer with WSOLA.
D/PjSipLogWriter: 16:39:58.701            pjsua_vid.c  ..Initializing video subsystem..
    16:39:58.701           openh264.cpp  ...OpenH264 codec initialized
    16:39:58.701           opengl_dev.c  ...OpenGL device initialized
E/libc: Access denied finding property "camera.hal1.packagelist"
W/PjSipService: type=1400 audit(0.0:7543): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=6323 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
W/PjSipService: type=1400 audit(0.0:7544): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=6323 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc: Access denied finding property "camera.hal1.packagelist"
D/PjSipLogWriter: 16:39:59.194          android_dev.c  ...Android video capture initialized with 2 device(s):
    16:39:59.195          android_dev.c  ... 0: Front camera
    16:39:59.195          android_dev.c  ...     supported format = NV21/2048x1080 NV21/1080x2048 NV21/1920x1080 NV21/1080x1920 NV21/1920x960 NV21/960x1920 NV21/1440x1080 NV21/1080x1440 NV21/1280x960 NV21/960x1280 NV21/1280x720 NV21/720x1280 NV21/1280x640 NV21/640x1280 NV21/864x480 NV21/480x864 NV21/800x480 NV21/480x800 NV21/768x432 NV21/432x768 NV21/720x480 NV21/480x720 NV21/640x640 NV21/640x640 NV21/640x480 NV21/480x640 NV21/480x640 NV21/640x480 NV21/640x360 NV21/360x640 NV21/576x432 NV21/432x576 NV21/480x360 NV21/360x480 NV21/480x320 NV21/320x480 NV21/384x288 NV21/288x384 NV21/352x288 NV21/288x352 NV21/320x240 NV21/240x320 NV21/240x320 NV21/320x240 NV21/240x160 NV21/160x240 NV21/176x144 NV21/144x176 NV21/144x176 NV21/176x144 NV21/160x120 NV21/120x160 YV12/2048x1080 YV12/1080x2048 YV12/1920x1080 YV12/1080x1920 YV12/1920x960 YV12/960x1920 YV12/1440x1080 YV12/1080x1440 YV12/1280x960 YV12/960x1280 YV12/1280x720 YV12/720x1280 YV12/1280x640 YV12/640x1280 YV12/864x480 YV12/480x864 YV12/800x480 YV12/480x800 YV12/768x432 YV12/432x768 YV12/720x480 YV12/480x720 YV12/640x640 YV12/640x640 YV12/640x480 YV12/480x640 YV12/480x640 YV12/640x480 YV12/640x360 YV12/360x640 YV12/576x432 YV12/432x576 YV12/480x360 YV12/360x480 YV12/480x320 YV12/320x480 YV12/384x288 YV12/288x384 YV12/352x288 YV12/288x352 YV12/320x240 YV12/240x320 YV12/240x320 YV12/320x240 YV12/240x160 YV12/160x240 YV12/176x144 YV12/144x176 YV12/144x176 YV12/176x144 YV12/160x120 YV12/120x160 I420/2048x1080 I420/1080x2048 I420/1920x1080 I420/1080x1920 I420/1920x960 I420/960x1920 I420/1440x1080 I420/1080x1440 I420/1280x960 I420/960x1280 I420/1280x720 I420/720x1280 I420/1280x640 I420/640x1280 I420/864x480 I420/480x864 I420/800x480 I420/480x800 I420/768x432 I420/432x768 I420/720x480 I420/480x720 I420/640x640 I420/640x640 
    16:39:59.195          android_dev.c  ... 1: Back camera
    16:39:59.195          android_dev.c  ...     supported format = NV21/2048x1080 NV21/1080x2048 NV21/1920x1080 NV21/1080x1920 NV21/1920x960 NV21/960x1920 NV21/1440x1080 NV21/1080x1440 NV21/1280x960 NV21/960x1280 NV21/1280x720 NV21/720x1280 NV21/1280x640 NV21/640x1280 NV21/864x480 NV21/480x864 NV21/800x480 NV21/480x800 NV21/768x432 NV21/432x768 NV21/720x480 NV21/480x720 NV21/640x640 NV21/640x640 NV21/640x480 NV21/480x640 NV21/480x640 NV21/640x480 NV21/640x360 NV21/360x640 NV21/576x432 NV21/432x576 NV21/480x360 NV21/360x480 NV21/480x320 NV21/320x480 NV21/384x288 NV21/288x384 NV21/352x288 NV21/288x352 NV21/320x240 NV21/240x320 NV21/240x320 NV21/320x240 NV21/240x160 NV21/160x240 NV21/176x144 NV21/144x176 NV21/144x176 NV21/176x144 NV21/160x120 NV21/120x160 YV12/2048x1080 YV12/1080x2048 YV12/1920x1080 YV12/1080x1920 YV12/1920x960 YV12/960x1920 YV12/1440x1080 YV12/1080x1440 YV12/1280x960 YV12/960x1280 YV12/1280x720 YV12/720x1280 YV12/1280x640 YV12/640x1280 YV12/864x480 YV12/480x864 YV12/800x480 YV12/480x800 YV12/768x432 YV12/432x768 YV12/720x480 YV12/480x720 YV12/640x640 YV12/640x640 YV12/640x480 YV12/480x640 YV12/480x640 YV12/640x480 YV12/640x360 YV12/360x640 YV12/576x432 YV12/432x576 YV12/480x360 YV12/360x480 YV12/480x320 YV12/320x480 YV12/384x288 YV12/288x384 YV12/352x288 YV12/288x352 YV12/320x240 YV12/240x320 YV12/240x320 YV12/320x240 YV12/240x160 YV12/160x240 YV12/176x144 YV12/144x176 YV12/144x176 YV12/176x144 YV12/160x120 YV12/120x160 I420/2048x1080 I420/1080x2048 I420/1920x1080 I420/1080x1920 I420/1920x960 I420/960x1920 I420/1440x1080 I420/1080x1440 I420/1280x960 I420/960x1280 I420/1280x720 I420/720x1280 I420/1280x640 I420/640x1280 I420/864x480 I420/480x864 I420/800x480 I420/480x800 I420/768x432 I420/432x768 I420/720x480 I420/480x720 I420/640x640 I420/640x640 
D/PjSipLogWriter: 16:39:59.196         colorbar_dev.c  ...Colorbar video src initialized with 2 device(s):
    16:39:59.196         colorbar_dev.c  ... 0: Colorbar generator
    16:39:59.196         colorbar_dev.c  ... 1: Colorbar-active
    16:39:59.196         sip_endpoint.c  .Module "mod-evsub" registered
    16:39:59.196         sip_endpoint.c  .Module "mod-presence" registered
    16:39:59.196                evsub.c  .Event pkg "presence" registered by mod-presence
    16:39:59.196         sip_endpoint.c  .Module "mod-mwi" registered
    16:39:59.196                evsub.c  .Event pkg "message-summary" registered by mod-mwi
    16:39:59.196         sip_endpoint.c  .Module "mod-refer" registered
    16:39:59.196                evsub.c  .Event pkg "refer" registered by mod-refer
D/PjSipLogWriter: 16:39:59.197         sip_endpoint.c  .Module "mod-pjsua-pres" registered
    16:39:59.197         sip_endpoint.c  .Module "mod-pjsua-im" registered
    16:39:59.197         sip_endpoint.c  .Module "mod-pjsua-options" registered
    16:39:59.197           pjsua_core.c  .1 SIP worker threads created
    16:39:59.197           pjsua_core.c  .pjsua version 2.7.1 for Linux-3.18.71/aarch64 initialized
    16:39:59.197           pjsua_core.c  .PJSUA state changed: CREATED --> INIT
D/PjSipLogWriter: 16:39:59.200           pjsua_core.c  SIP UDP socket reachable at 192.168.0.101:49909
    16:39:59.200        udp0x6fad0e4c00  SIP UDP transport started, published address is 192.168.0.101:49909
D/PjSipLogWriter: 16:39:59.203            tcptp:39678  SIP TCP listener ready for incoming connections at 192.168.0.101:39678
D/PjSipLogWriter: 16:39:59.206            tlstp:43328  SIP TLS listener is ready for incoming connections at 192.168.0.101:43328
    16:39:59.206           pjsua_core.c  PJSUA state changed: INIT --> STARTING
    16:39:59.206         sip_endpoint.c  .Module "mod-unsolicited-mwi" registered
    16:39:59.206           pjsua_core.c  .PJSUA state changed: STARTING --> RUNNING
_D/PjSipService: Handle "call_make" action ({"destination":"sip:3333@13.72.66.225:5080","callback_id":3,"account_id":0})
D/PjSipBroadcastReceiver: Received "com.carusto.handled" response from service ({"exception":"Account with specified \"0\" id not found","callback_id":3})
W/PjSipBroadcastReceiver: Callback executed with exception state: Account with specified "0" id not found
V/FA: Inactivity, disconnecting from the service_`

Thank you so much

**Comment by willnaoosmith** [comment] 2021-07-30 11:45
The time of the call being marked as not answered depends more on your SIP/VOIP server than the application itself.

Also, there's more logs than that, right?

Look after your android permissions, after android 10 you will need the SYSTEM_ALERT_WINDOW (aka as "Draw over other apps" permission).

Would reccomend looking on your server if the call is ended by time (Normal workflow) or if your app stops sending keep alive packets, so your server ends the call because it thinks your phone isn't online anymore.

**Comment by ReactNativeDev2296** [comment] 2021-07-30 11:49
Hi @willnaoosmith ,

it is working fine in foreground but i am facing issue in background android side and in IOS working fine .

**Comment by willnaoosmith** [comment] 2021-07-30 12:02
IOS is receiving calls fine?

wow, that's new haha. did you implement voip push?


So, did you looked on your voip server whats the flow of the call? Or maybe the last status of the call when terminated.

**Comment by ReactNativeDev2296** [comment] 2021-08-02 05:11
yes @willnaoosmith  in IOS working fine getting call and after 4 min i accepted it is working,
and i am using tcp server

**Comment by willnaoosmith** [comment] 2021-08-02 14:02
Ok then.
Did you look on your server what's the problem?

**Comment by ReactNativeDev2296** [comment] 2021-08-06 09:09
Hello @willnaoosmith ,

**when i try to accept call registration response(background) :-**
 _registration: AccountRegistration
_statusText: "In Progress"
_status: "PJSIP_SC_TRYING"
_reason: undefined			
_active: false  

**Error:-** Account with id ''1" is not found

**Comment by willnaoosmith** [comment] 2021-08-06 10:57
The problem is:

For some reason the account registration flow it's not being complete, which means one packet (Probably the last packet from the registration flow, which comes from the server) it's not going on the app itself, so the app cannot create account with id 1, meaning it doesn't exist.

The file `android/src/main/java/com/carusto/ReactNativePjSip/PjSipService.java` contains the code for the account creation (And almost everything else)

Probably, given it's time after the account creation, one of these functions will fail:

1. doAccountCreate (Probably this one).
2. handleAccountRegister.
3. handleAccountCreate.

Once they fail, they will trigger a `catch` block, so the code on this catch block will run and show you what's the error (Probably timeout error).


So, you mostly need to see on your server why the registration flow isn't being complete.

**Comment by ReactNativeDev2296** [comment] 2021-08-06 11:02
ok @willnaoosmith ,
thank you so much for help

**Comment by ReactNativeDev2296** [comment] 2021-08-09 05:58
Hi @willnaoosmith ,
**when try to accept call (android side log)** 
`D/RNFirebaseMsgReceiver: broadcast received for message
V/FA: Connecting to remote service
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 1
V/FA: Inactivity, disconnecting from the service
I/zygote64: Explicit concurrent copying GC freed 27258(1475KB) AllocSpace objects, 12(312KB) LOS objects, 42% free, 5MB/9MB, paused 199us total 91.162ms
D/PjSipLogWriter: 11:23:28.878           pjsua_core.c !Shutting down, flags=0...
    11:23:28.878           pjsua_core.c  PJSUA state changed: RUNNING --> CLOSING
D/PjSipLogWriter: 11:23:28.887           pjsua_call.c  .Hangup all calls..
D/PjSipLogWriter: 11:23:28.887          pjsua_media.c  .Call 0: deinitializing media..
    11:23:28.888          pjsua_media.c  .Call 1: deinitializing media..
    11:23:28.888          pjsua_media.c  .Call 2: deinitializing media..
    11:23:28.888          pjsua_media.c  .Call 3: deinitializing media..
    11:23:28.888           pjsua_pres.c  .Shutting down presence..
    11:23:28.888            pjsua_acc.c  .Acc 0: setting unregistration..
D/PjSipLogWriter: 11:23:28.889               endpoint  ..Request msg REGISTER/cseq=44267 (tdta0x70c4ff60a8) created.
    11:23:28.889        tsx0x70b09e00a8  ...Transaction created for Request msg REGISTER/cseq=44268 (tdta0x70c4ff60a8)
    11:23:28.889        tsx0x70b09e00a8  ..Sending Request msg REGISTER/cseq=44268 (tdta0x70c4ff60a8) in state Null
    11:23:28.889          sip_resolve.c  ...Target '13.72.66.225:5080' type=TCP resolved to '13.72.66.225:5080' type=TCP (TCP transport)
D/PjSipLogWriter: 11:23:28.890           pjsua_core.c  ...TX 722 bytes Request msg REGISTER/cseq=44268 (tdta0x70c4ff60a8) to TCP 13.72.66.225:5080:
    REGISTER sip:13.72.66.225:5080 SIP/2.0
    Via: SIP/2.0/TCP 103.228.145.6:64513;rport;branch=z9hG4bKPjd040d95e-c485-4672-b9f1-e34f3d6a4da1;alias
    Max-Forwards: 70
    From: "84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer" <sip:84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer@13.72.66.225>;tag=077e7177-6704-4097-b380-12509fb06b84
    To: "84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer" <sip:84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer@13.72.66.225>
    Call-ID: ce63617b-5e0c-4f4d-ac30-985153600ed0
    CSeq: 44268 REGISTER
    User-Agent: VMAX Fone
    Contact: <sip:84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer@103.228.145.6:64513;transport=TCP;im-type=sip;ob>
    Expires: 0
    Content-Length:  0
    
    
    --end msg--
    11:23:28.890        tsx0x70b09e00a8  ...State changed from Null to Calling, event=TX_MSG
    11:23:28.890            pjsua_acc.c  ..Acc 0: Unregistration sent
D/PjSipLogWriter: 11:23:29.128         sip_endpoint.c  .Processing incoming message: Response msg 401/REGISTER/cseq=44268 (rdata0x70b141db30)
D/PjSipLogWriter: 11:23:29.128           pjsua_core.c  ..RX 826 bytes Response msg 401/REGISTER/cseq=44268 (rdata0x70b141db30) from TCP 13.72.66.225:5080:
    SIP/2.0 401 Unauthorized
    Via: SIP/2.0/TCP 103.228.145.6:64513;rport=64513;branch=z9hG4bKPjd040d95e-c485-4672-b9f1-e34f3d6a4da1;alias
    From: "84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer" <sip:84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer@13.72.66.225>;tag=077e7177-6704-4097-b380-12509fb06b84
    To: "84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer" <sip:84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer@13.72.66.225>;tag=1Z64HmjygyXtQ
    Call-ID: ce63617b-5e0c-4f4d-ac30-985153600ed0
    CSeq: 44268 REGISTER
    User-Agent: FreeSWITCH
    Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY
    Supported: timer, path, replaces
    WWW-Authenticate: Digest realm="13.72.66.225", nonce="86c6d551-55e5-42a4-919a-29723b409478", algorithm=MD5, qop="auth"
    Content-Length: 0
    
    
    --end msg--
    11:23:29.129        tsx0x70b09e00a8  ..Incoming Response msg 401/REGISTER/cseq=44268 (rdata0x70b141db30) in state Calling
    11:23:29.129        tsx0x70b09e00a8  ...State changed from Calling to Completed, event=RX_MSG
D/PjSipLogWriter: 11:23:29.130        tsx0x70b15cb0a8  .....Transaction created for Request msg REGISTER/cseq=44269 (tdta0x70c4ff60a8)
    11:23:29.130        tsx0x70b15cb0a8  ....Sending Request msg REGISTER/cseq=44269 (tdta0x70c4ff60a8) in state Null
D/PjSipLogWriter: 11:23:29.130               endpoint  .....Request msg REGISTER/cseq=44269 (tdta0x70c4ff60a8): skipping target resolution because address is already set
    11:23:29.131           pjsua_core.c  .....TX 1038 bytes Request msg REGISTER/cseq=44269 (tdta0x70c4ff60a8) to TCP 13.72.66.225:5080:
    REGISTER sip:13.72.66.225:5080 SIP/2.0
    Via: SIP/2.0/TCP 103.228.145.6:64513;rport;branch=z9hG4bKPjdbb3f95c-0760-450d-b1fd-ee1c4b2d7c75;alias
    Max-Forwards: 70
    From: "84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer" <sip:84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer@13.72.66.225>;tag=077e7177-6704-4097-b380-12509fb06b84
    To: "84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer" <sip:84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer@13.72.66.225>
    Call-ID: ce63617b-5e0c-4f4d-ac30-985153600ed0
    CSeq: 44269 REGISTER
    User-Agent: VMAX Fone
    Contact: <sip:84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer@103.228.145.6:64513;transport=TCP;im-type=sip;ob>
    Expires: 0
    Authorization: Digest username="84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer", realm="13.72.66.225", nonce="86c6d551-55e5-42a4-919a-29723b409478", uri="sip:13.72.66.225:5080", response="4dceb539f787dd7209b1e3cd06be3678", algorithm=MD5, cnonce="4fe09a53-d25b-4186-a2de-3bd9a4050d39", qop=auth, nc=00000001
    Content-Length:  0
    
    
    --end msg--
D/PjSipLogWriter: 11:23:29.131        tsx0x70b15cb0a8  .....State changed from Null to Calling, event=TX_MSG
    11:23:29.132        tsx0x70b09e00a8  .Timeout timer event
    11:23:29.132        tsx0x70b09e00a8  ..State changed from Completed to Terminated, event=TIMER
    11:23:29.132        tsx0x70b09e00a8  .Timeout timer event
    11:23:29.132        tsx0x70b09e00a8  ..State changed from Terminated to Destroyed, event=TIMER
    11:23:29.132        tsx0x70b09e00a8  .Transaction destroyed!
D/PjSipLogWriter: 11:23:29.360         sip_endpoint.c  .Processing incoming message: Response msg 200/REGISTER/cseq=44269 (rdata0x70b141db30)
    11:23:29.361           pjsua_core.c  ..RX 733 bytes Response msg 200/REGISTER/cseq=44269 (rdata0x70b141db30) from TCP 13.72.66.225:5080:
    SIP/2.0 200 OK
    Via: SIP/2.0/TCP 103.228.145.6:64513;rport=64513;branch=z9hG4bKPjdbb3f95c-0760-450d-b1fd-ee1c4b2d7c75;alias
    From: "84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer" <sip:84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer@13.72.66.225>;tag=077e7177-6704-4097-b380-12509fb06b84
    To: "84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer" <sip:84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer@13.72.66.225>;tag=28ZXKF31D7KDK
    Call-ID: ce63617b-5e0c-4f4d-ac30-985153600ed0
    CSeq: 44269 REGISTER
    Date: Mon, 09 Aug 2021 05:53:13 GMT
    User-Agent: FreeSWITCH
    Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY
    Supported: timer, path, replaces
    Content-Length: 0
    
    
    --end msg--
    11:23:29.361        tsx0x70b15cb0a8  ..Incoming Response msg 200/REGISTER/cseq=44269 (rdata0x70b141db30) in state Calling
    11:23:29.361        tsx0x70b15cb0a8  ...State changed from Calling to Completed, event=RX_MSG
D/PjSipLogWriter: 11:23:29.361            pjsua_acc.c  .....84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer <sip:84d4095c-f579-4453-aeae-47123d8ff944_Testing_Developer@13.72.66.225:5080>: unregistration success
W/PjSipService: Creating notification
W/PjSipService: Error starting foreground notification
    java.lang.ClassNotFoundException: com.vmaxfone.MainActivity
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at com.carusto.ReactNativePjSip.PjSipService.createRunningNotification(PjSipService.java:528)
        at com.carusto.ReactNativePjSip.PjSipService.emmitRegistrationChanged(PjSipService.java:1089)
        at com.carusto.ReactNativePjSip.PjSipAccount.onRegState(PjSipAccount.java:58)
        at org.pjsip.pjsua2.pjsua2JNI.SwigDirector_Account_onRegState(pjsua2JNI.java:2515)
        at org.pjsip.pjsua2.pjsua2JNI.Endpoint_libDestroy___SWIG_1(Native Method)
        at org.pjsip.pjsua2.Endpoint.libDestroy_(Endpoint.java:113)
        at org.pjsip.pjsua2.Endpoint.libDestroy(Endpoint.java:60)
        at com.carusto.ReactNativePjSip.PjSipService.onDestroy(PjSipService.java:296)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3546)
        at android.app.ActivityThread.-wrap26(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1726)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.vmaxfone.MainActivity" on path: DexPathList[[zip file "/data/app/com.logicmark.connectedguardian-XEWVivNgfFf88EeztNqr9Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.logicmark.connectedguardian-XEWVivNgfFf88EeztNqr9Q==/lib/arm64, /data/app/com.logicmark.connectedguardian-XEWVivNgfFf88EeztNqr9Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at java.lang.Class.forName(Class.java:378) 
        at com.carusto.ReactNativePjSip.PjSipService.createRunningNotification(PjSipService.java:528) 
        at com.carusto.ReactNativePjSip.PjSipService.emmitRegistrationChanged(PjSipService.java:1089) 
        at com.carusto.ReactNativePjSip.PjSipAccount.onRegState(PjSipAccount.java:58) 
        at org.pjsip.pjsua2.pjsua2JNI.SwigDirector_Account_onRegState(pjsua2JNI.java:2515) 
        at org.pjsip.pjsua2.pjsua2JNI.Endpoint_libDestroy___SWIG_1(Native Method) 
        at org.pjsip.pjsua2.Endpoint.libDestroy_(Endpoint.java:113) 
        at org.pjsip.pjsua2.Endpoint.libDestroy(Endpoint.java:60) 
        at com.carusto.ReactNativePjSip.PjSipService.onDestroy(PjSipService.java:296) 
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3546) 
        at android.app.ActivityThread.-wrap26(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1726) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6651) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
D/PjSipLogWriter: 11:23:29.381        tsx0x70b15cb0a8  .Timeout timer event
D/PjSipLogWriter: 11:23:29.382        tsx0x70b15cb0a8  ..State changed from Completed to Terminated, event=TIMER
D/PjSipLogWriter: 11:23:29.383        tsx0x70b15cb0a8  .Timeout timer event
    11:23:29.384        tsx0x70b15cb0a8  ..State changed from Terminated to Destroyed, event=TIMER
    11:23:29.384       tdta0x70c4ff60a8  ...Destroying txdata Request msg REGISTER/cseq=44269 (tdta0x70c4ff60a8)
    11:23:29.384        tsx0x70b15cb0a8  .Transaction destroyed!
D/PjSipLogWriter: 11:23:29.962           pjsua_core.c  .Destroying...
    11:23:29.962          pjsua_media.c  .Shutting down media..
D/PjSipLogWriter: 11:23:30.354            pjsua_vid.c  ..Destroying video subsystem..
    11:23:30.354            pjsua_vid.c  ...Window 0: destroying..
    11:23:30.354            pjsua_vid.c  ...Window 1: destroying..
D/PjSipLogWriter: 11:23:30.354            pjsua_vid.c  ...Window 2: destroying..
    11:23:30.355            pjsua_vid.c  ...Window 3: destroying..
    11:23:30.355            pjsua_vid.c  ...Window 4: destroying..
    11:23:30.355            pjsua_vid.c  ...Window 5: destroying..
    11:23:30.355            pjsua_vid.c  ...Window 6: destroying..
    11:23:30.355            pjsua_vid.c  ...Window 7: destroying..
D/PjSipLogWriter: 11:23:30.356            pjsua_vid.c  ...Window 8: destroying..
    11:23:30.356            pjsua_vid.c  ...Window 9: destroying..
    11:23:30.356            pjsua_vid.c  ...Window 10: destroying..
    11:23:30.356            pjsua_vid.c  ...Window 11: destroying..
D/PjSipLogWriter: 11:23:30.356            pjsua_vid.c  ...Window 12: destroying..
    11:23:30.357            pjsua_vid.c  ...Window 13: destroying..
    11:23:30.357            pjsua_vid.c  ...Window 14: destroying..
    11:23:30.357            pjsua_vid.c  ...Window 15: destroying..
D/PjSipLogWriter: 11:23:30.358           opensl_dev.c  ..OpenSL sound library shutting down..
D/PjSipLogWriter: 11:23:30.358         sip_endpoint.c  .Destroying endpoing instance..
    11:23:30.359      sip_transaction.c  .Stopping transaction layer module
    11:23:30.359      sip_transaction.c  .Stopped transaction layer module
    11:23:30.359         sip_endpoint.c  .Module "mod-unsolicited-mwi" unregistered
    11:23:30.359         sip_endpoint.c  .Module "mod-pjsua-options" unregistered
    11:23:30.359         sip_endpoint.c  .Module "mod-pjsua-im" unregistered
D/PjSipLogWriter: 11:23:30.359         sip_endpoint.c  .Module "mod-pjsua-pres" unregistered
    11:23:30.360         sip_endpoint.c  .Module "mod-pjsua" unregistered
    11:23:30.360         sip_endpoint.c  .Module "mod-stateful-util" unregistered
    11:23:30.360         sip_endpoint.c  .Module "mod-refer" unregistered
    11:23:30.360         sip_endpoint.c  .Module "mod-mwi" unregistered
    11:23:30.360         sip_endpoint.c  .Module "mod-presence" unregistered
D/PjSipLogWriter: 11:23:30.361         sip_endpoint.c  .Module "mod-evsub" unregistered
    11:23:30.361         sip_endpoint.c  .Module "mod-invite" unregistered
    11:23:30.361         sip_endpoint.c  .Module "mod-100rel" unregistered
    11:23:30.361         sip_endpoint.c  .Module "mod-ua" unregistered
    11:23:30.361      sip_transaction.c  .Transaction layer module destroyed
D/PjSipLogWriter: 11:23:30.361         sip_endpoint.c  .Module "mod-tsx-layer" unregistered
    11:23:30.362         sip_endpoint.c  .Module "mod-msg-print" unregistered
    11:23:30.362         sip_endpoint.c  .Module "mod-pjsua-log" unregistered
    11:23:30.362        sip_transport.c  .Destroying transport manager
D/PjSipLogWriter: 11:23:30.364        udp0x70b3b64800  .SIP UDP transport destroyed
    11:23:30.364       tcpc0x70b141d828  .TCP transport destroyed normally
D/PjSipLogWriter: 11:23:30.364            tcptp:39306  .SIP TCP transport destroyed
    11:23:30.365            tlstp:42542  .SIP TLS transport destroyed
    11:23:30.365         sip_endpoint.c  .Endpoint 0x70b27680a8 destroyed
D/PjSipLogWriter: 11:23:30.365           pjsua_core.c  .PJSUA state changed: CLOSING --> NULL
    11:23:30.366           pjsua_core.c  .PJSUA destroyed...`

**Comment by willnaoosmith** [comment] 2021-08-09 10:55
ps: You need to rename everything called "vmax" to your app name or something, this module was made to another app, you kinda need to change it.

**Comment by ReactNativeDev2296** [comment] 2021-08-12 05:32
Hi @willnaoosmith 
i changed "vmax" to my module name.
it is GC Related issue ? when app is background and  pjsip is destroyed.........
`Fatal signal 6 (SIGABRT), code -6 in tid 13038 (PjSipService), pid 12556 (nnectedguardian)`

**Closed as completed** 2021-10-12 09:18 UTC
